var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/extension/import/route.js")
R.c("server/chunks/[root-of-the-server]__0zhif7h._.js")
R.c("server/chunks/_0.k7p5x._.js")
R.c("server/chunks/_0v_j7b4._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/node_modules_0.81f0j._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_next-internal_server_app_api_extension_import_route_actions_0q~ipa4.js")
R.m(8833)
module.exports=R.m(8833).exports
