var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/competitors/search/route.js")
R.c("server/chunks/[root-of-the-server]__00aljkk._.js")
R.c("server/chunks/[root-of-the-server]__0pxatrj._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/_0n30q_1._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/node_modules_0.81f0j._.js")
R.c("server/chunks/_next-internal_server_app_api_competitors_search_route_actions_0igb.4z.js")
R.m(540730)
module.exports=R.m(540730).exports
