var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/alerts/route.js")
R.c("server/chunks/[root-of-the-server]__0u8ek71._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/[root-of-the-server]__0pxatrj._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_alerts_route_actions_078xzkr.js")
R.m(592027)
module.exports=R.m(592027).exports
