var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/visibility/audit/route.js")
R.c("server/chunks/[root-of-the-server]__0le2ccc._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/[root-of-the-server]__0j2~4y-._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_visibility_audit_route_actions_11unzba.js")
R.m(977922)
module.exports=R.m(977922).exports
