var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/metering/route.js")
R.c("server/chunks/[root-of-the-server]__0on~.rz._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/[root-of-the-server]__0pxatrj._.js")
R.c("server/chunks/[root-of-the-server]__0jhs7.w._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/_next-internal_server_app_api_metering_route_actions_0-c-svl.js")
R.m(824378)
module.exports=R.m(824378).exports
