var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/monitoring/report/route.js")
R.c("server/chunks/[root-of-the-server]__0acof6a._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/_12syje_._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/[root-of-the-server]__0pxatrj._.js")
R.c("server/chunks/_next-internal_server_app_api_monitoring_report_route_actions_0~kvf6_.js")
R.m(369074)
module.exports=R.m(369074).exports
