// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/about" | "/[locale]/act-on-signals" | "/[locale]/ai-visibility" | "/[locale]/customer-feedback" | "/[locale]/guide" | "/[locale]/guide-visibilite-ia" | "/[locale]/how-to" | "/[locale]/legal/disclaimer" | "/[locale]/legal/privacy" | "/[locale]/legal/terms" | "/[locale]/live-monitoring" | "/[locale]/reputation-engine" | "/[locale]/reputation-risk" | "/analytics" | "/billing" | "/campaigns" | "/customers" | "/dashboard" | "/extension" | "/f/[id]" | "/feedback" | "/imports" | "/intelligence" | "/intelligence/competitors" | "/intelligence/risk" | "/login" | "/monitoring" | "/recovery" | "/register" | "/review-links" | "/settings" | "/team" | "/templates" | "/visibility"
type AppRouteHandlerRoutes = "/api/admin/queues" | "/api/ai/alerts" | "/api/ai/analyze" | "/api/ai/reputation" | "/api/ai/respond" | "/api/ai/visibility/attribute" | "/api/ai/visibility/audit" | "/api/ai/visibility/benchmark" | "/api/ai/visibility/monitor" | "/api/ai/visibility/prompts" | "/api/ai/visibility/prompts/history" | "/api/ai/visibility/prompts/run" | "/api/ai/visibility/remediate" | "/api/ai/visibility/report" | "/api/analytics" | "/api/auth/[...nextauth]" | "/api/auth/register" | "/api/av/audit" | "/api/av/audit/report" | "/api/billing" | "/api/campaigns" | "/api/campaigns/[id]" | "/api/competitors" | "/api/competitors/[id]" | "/api/competitors/[id]/snapshots" | "/api/competitors/refresh" | "/api/competitors/search" | "/api/compliance/erase" | "/api/compliance/export" | "/api/customers" | "/api/customers/[id]" | "/api/enterprise/inquiry" | "/api/extension/import" | "/api/extension/token" | "/api/feedback" | "/api/feedback/[token]" | "/api/imports" | "/api/imports/[id]" | "/api/imports/[id]/commit" | "/api/intelligence/report" | "/api/metering" | "/api/metering/history" | "/api/monitoring/report" | "/api/monitoring/reviews" | "/api/monitoring/sources" | "/api/monitoring/sources/[id]" | "/api/onboarding" | "/api/recovery" | "/api/recovery/[id]" | "/api/reputation/alerts" | "/api/reputation/config" | "/api/reputation/risk" | "/api/review-links" | "/api/review-links/[id]" | "/api/review-links/[id]/qr" | "/api/signals" | "/api/team" | "/api/team/[id]" | "/api/templates" | "/api/templates/[id]" | "/api/tenants" | "/api/tenants/active" | "/api/webhooks" | "/api/webhooks/brevo"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/about": { "locale": string; }
  "/[locale]/act-on-signals": { "locale": string; }
  "/[locale]/ai-visibility": { "locale": string; }
  "/[locale]/customer-feedback": { "locale": string; }
  "/[locale]/guide": { "locale": string; }
  "/[locale]/guide-visibilite-ia": { "locale": string; }
  "/[locale]/how-to": { "locale": string; }
  "/[locale]/legal/disclaimer": { "locale": string; }
  "/[locale]/legal/privacy": { "locale": string; }
  "/[locale]/legal/terms": { "locale": string; }
  "/[locale]/live-monitoring": { "locale": string; }
  "/[locale]/reputation-engine": { "locale": string; }
  "/[locale]/reputation-risk": { "locale": string; }
  "/analytics": {}
  "/api/admin/queues": {}
  "/api/ai/alerts": {}
  "/api/ai/analyze": {}
  "/api/ai/reputation": {}
  "/api/ai/respond": {}
  "/api/ai/visibility/attribute": {}
  "/api/ai/visibility/audit": {}
  "/api/ai/visibility/benchmark": {}
  "/api/ai/visibility/monitor": {}
  "/api/ai/visibility/prompts": {}
  "/api/ai/visibility/prompts/history": {}
  "/api/ai/visibility/prompts/run": {}
  "/api/ai/visibility/remediate": {}
  "/api/ai/visibility/report": {}
  "/api/analytics": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/register": {}
  "/api/av/audit": {}
  "/api/av/audit/report": {}
  "/api/billing": {}
  "/api/campaigns": {}
  "/api/campaigns/[id]": { "id": string; }
  "/api/competitors": {}
  "/api/competitors/[id]": { "id": string; }
  "/api/competitors/[id]/snapshots": { "id": string; }
  "/api/competitors/refresh": {}
  "/api/competitors/search": {}
  "/api/compliance/erase": {}
  "/api/compliance/export": {}
  "/api/customers": {}
  "/api/customers/[id]": { "id": string; }
  "/api/enterprise/inquiry": {}
  "/api/extension/import": {}
  "/api/extension/token": {}
  "/api/feedback": {}
  "/api/feedback/[token]": { "token": string; }
  "/api/imports": {}
  "/api/imports/[id]": { "id": string; }
  "/api/imports/[id]/commit": { "id": string; }
  "/api/intelligence/report": {}
  "/api/metering": {}
  "/api/metering/history": {}
  "/api/monitoring/report": {}
  "/api/monitoring/reviews": {}
  "/api/monitoring/sources": {}
  "/api/monitoring/sources/[id]": { "id": string; }
  "/api/onboarding": {}
  "/api/recovery": {}
  "/api/recovery/[id]": { "id": string; }
  "/api/reputation/alerts": {}
  "/api/reputation/config": {}
  "/api/reputation/risk": {}
  "/api/review-links": {}
  "/api/review-links/[id]": { "id": string; }
  "/api/review-links/[id]/qr": { "id": string; }
  "/api/signals": {}
  "/api/team": {}
  "/api/team/[id]": { "id": string; }
  "/api/templates": {}
  "/api/templates/[id]": { "id": string; }
  "/api/tenants": {}
  "/api/tenants/active": {}
  "/api/webhooks": {}
  "/api/webhooks/brevo": {}
  "/billing": {}
  "/campaigns": {}
  "/customers": {}
  "/dashboard": {}
  "/extension": {}
  "/f/[id]": { "id": string; }
  "/feedback": {}
  "/imports": {}
  "/intelligence": {}
  "/intelligence/competitors": {}
  "/intelligence/risk": {}
  "/login": {}
  "/monitoring": {}
  "/recovery": {}
  "/register": {}
  "/review-links": {}
  "/settings": {}
  "/team": {}
  "/templates": {}
  "/visibility": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
