// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/extension/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/extension">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/extension/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feedback">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/imports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/imports">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/imports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/intelligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intelligence">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/intelligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitoring">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/recovery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recovery">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/recovery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/review-links/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/review-links">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/review-links/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/visibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/visibility">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/visibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/about">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/act-on-signals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/act-on-signals">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/act-on-signals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/ai-visibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ai-visibility">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/ai-visibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/customer-feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/customer-feedback">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/customer-feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/guide-visibilite-ia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/guide-visibilite-ia">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/guide-visibilite-ia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/guide">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/how-to/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/how-to">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/how-to/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/legal/disclaimer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/legal/disclaimer">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/legal/disclaimer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/legal/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/legal/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/legal/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/legal/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/legal/terms">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/legal/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/live-monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/live-monitoring">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/live-monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/reputation-engine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/reputation-engine">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/reputation-engine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/reputation-risk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/reputation-risk">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/reputation-risk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/f/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/f/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/f/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/intelligence/competitors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intelligence/competitors">> = Specific
  const handler = {} as typeof import("../../src/app/intelligence/competitors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/intelligence/risk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intelligence/risk">> = Specific
  const handler = {} as typeof import("../../src/app/intelligence/risk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/queues/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/queues">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/queues/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/analyze">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/reputation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/reputation">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/reputation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/respond/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/respond">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/respond/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/visibility/attribute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/visibility/attribute">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/visibility/attribute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/visibility/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/visibility/audit">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/visibility/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/visibility/benchmark/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/visibility/benchmark">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/visibility/benchmark/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/visibility/monitor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/visibility/monitor">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/visibility/monitor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/visibility/prompts/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/visibility/prompts/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/visibility/prompts/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/visibility/prompts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/visibility/prompts">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/visibility/prompts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/visibility/prompts/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/visibility/prompts/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/visibility/prompts/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/visibility/remediate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/visibility/remediate">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/visibility/remediate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/visibility/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/visibility/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/visibility/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/av/audit/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/av/audit/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/av/audit/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/av/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/av/audit">> = Specific
  const handler = {} as typeof import("../../src/app/api/av/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/campaigns/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/campaigns/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/campaigns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/api/campaigns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitors/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitors/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitors/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitors/[id]/snapshots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitors/[id]/snapshots">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitors/[id]/snapshots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitors/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitors/refresh">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitors/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitors">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitors/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitors/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitors/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/compliance/erase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/erase">> = Specific
  const handler = {} as typeof import("../../src/app/api/compliance/erase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/compliance/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/compliance/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/customers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customers">> = Specific
  const handler = {} as typeof import("../../src/app/api/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/enterprise/inquiry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enterprise/inquiry">> = Specific
  const handler = {} as typeof import("../../src/app/api/enterprise/inquiry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/extension/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/extension/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/extension/token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension/token">> = Specific
  const handler = {} as typeof import("../../src/app/api/extension/token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/feedback/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/api/feedback/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback">> = Specific
  const handler = {} as typeof import("../../src/app/api/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/imports/[id]/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imports/[id]/commit">> = Specific
  const handler = {} as typeof import("../../src/app/api/imports/[id]/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/imports/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imports/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/imports/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/imports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imports">> = Specific
  const handler = {} as typeof import("../../src/app/api/imports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/intelligence/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intelligence/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/intelligence/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/metering/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metering/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/metering/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/metering/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metering">> = Specific
  const handler = {} as typeof import("../../src/app/api/metering/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/sources/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/sources/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/sources/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/sources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/sources">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/sources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/onboarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/api/onboarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recovery/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recovery/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/recovery/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recovery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recovery">> = Specific
  const handler = {} as typeof import("../../src/app/api/recovery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reputation/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reputation/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/reputation/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reputation/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reputation/config">> = Specific
  const handler = {} as typeof import("../../src/app/api/reputation/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reputation/risk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reputation/risk">> = Specific
  const handler = {} as typeof import("../../src/app/api/reputation/risk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/review-links/[id]/qr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review-links/[id]/qr">> = Specific
  const handler = {} as typeof import("../../src/app/api/review-links/[id]/qr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/review-links/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review-links/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/review-links/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/review-links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review-links">> = Specific
  const handler = {} as typeof import("../../src/app/api/review-links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signals">> = Specific
  const handler = {} as typeof import("../../src/app/api/signals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/team/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/team/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/team/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team">> = Specific
  const handler = {} as typeof import("../../src/app/api/team/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/templates/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/templates/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates">> = Specific
  const handler = {} as typeof import("../../src/app/api/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tenants/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenants/active">> = Specific
  const handler = {} as typeof import("../../src/app/api/tenants/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tenants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenants">> = Specific
  const handler = {} as typeof import("../../src/app/api/tenants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/brevo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/brevo">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/brevo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
