var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/competitors/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__0x5gu97._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/[root-of-the-server]__0j2~4y-._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_next-internal_server_app_api_competitors_[id]_route_actions_0dzxs_b.js")
R.m(282262)
module.exports=R.m(282262).exports
