var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/imports/route.js")
R.c("server/chunks/[root-of-the-server]__0gh8765._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/[root-of-the-server]__0pxatrj._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/_0iur93m._.js")
R.c("server/chunks/_next-internal_server_app_api_imports_route_actions_0bzim2-.js")
R.m(407560)
module.exports=R.m(407560).exports
