var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/competitors/refresh/route.js")
R.c("server/chunks/[root-of-the-server]__0qpy2r8._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/[root-of-the-server]__0pxatrj._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/node_modules_0.81f0j._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/_next-internal_server_app_api_competitors_refresh_route_actions_130bgs..js")
R.m(296417)
module.exports=R.m(296417).exports
