var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/webhooks/route.js")
R.c("server/chunks/[externals]__0wktl12._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/[root-of-the-server]__11895jh._.js")
R.c("server/chunks/_0bx.0c0._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/_next-internal_server_app_api_webhooks_route_actions_06k06sn.js")
R.m(487004)
module.exports=R.m(487004).exports
