var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/register/route.js")
R.c("server/chunks/[root-of-the-server]__05cz7kz._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0n.d9i.._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_register_route_actions_096_y_i.js")
R.m(606706)
module.exports=R.m(606706).exports
