var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/monitoring/reviews/route.js")
R.c("server/chunks/[root-of-the-server]__0c82p1o._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/[root-of-the-server]__0pxatrj._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_next-internal_server_app_api_monitoring_reviews_route_actions_0y4u5lx.js")
R.m(373784)
module.exports=R.m(373784).exports
