var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/register/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~7oiw1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0knlbee._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0tfxxt_.js")
R.c("server/chunks/ssr/[root-of-the-server]__0laxfye._.js")
R.c("server/chunks/ssr/node_modules_12pcxnx._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0quwrp9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_127nkdq._.js")
R.c("server/chunks/ssr/node_modules_next_0q16cuu._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ve2ws3._.js")
R.c("server/chunks/ssr/src_lib_i18n_content_ts_13ep3eb._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(auth)_register_page_actions_02nrb_5.js")
R.m(256615)
module.exports=R.m(256615).exports
