var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/intelligence/competitors/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~~q-za._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0knlbee._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0ehnges.js")
R.c("server/chunks/ssr/[root-of-the-server]__0laxfye._.js")
R.c("server/chunks/ssr/node_modules_12pcxnx._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0quwrp9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_intelligence_competitors_page_actions_0nsr4op.js")
R.m(400146)
module.exports=R.m(400146).exports
