var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/reputation/risk/route.js")
R.c("server/chunks/[root-of-the-server]__12f5lnc._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/[root-of-the-server]__0pxatrj._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/_next-internal_server_app_api_reputation_risk_route_actions_0kekgru.js")
R.m(363100)
module.exports=R.m(363100).exports
