var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/review-links/[id]/qr/route.js")
R.c("server/chunks/[root-of-the-server]__0-pzxhe._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/[root-of-the-server]__0~3ebqi._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/_0e6gkgd._.js")
R.c("server/chunks/_next-internal_server_app_api_review-links_[id]_qr_route_actions_05a~1ps.js")
R.m(166635)
module.exports=R.m(166635).exports
