var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/monitoring/sources/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__0mh2bt~._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/[root-of-the-server]__0j2~4y-._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/_next-internal_server_app_api_monitoring_sources_[id]_route_actions_04q3u~l.js")
R.m(336915)
module.exports=R.m(336915).exports
