var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/competitors/route.js")
R.c("server/chunks/[root-of-the-server]__0j2~4y-._.js")
R.c("server/chunks/[root-of-the-server]__0fcx98u._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/_0n30q_1._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/node_modules_0.81f0j._.js")
R.c("server/chunks/_next-internal_server_app_api_competitors_route_actions_00otk7u.js")
R.m(869097)
module.exports=R.m(869097).exports
