var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/reputation/route.js")
R.c("server/chunks/[root-of-the-server]__0w~g.mx._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/[root-of-the-server]__0pxatrj._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/_0rubf_r._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_reputation_route_actions_0akm312.js")
R.m(256721)
module.exports=R.m(256721).exports
