var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/customers/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__0uygctc._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/_next-internal_server_app_api_customers_[id]_route_actions_03s_11l.js")
R.m(358296)
module.exports=R.m(358296).exports
