var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/extension/token/route.js")
R.c("server/chunks/[root-of-the-server]__0wmzmth._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/_next-internal_server_app_api_extension_token_route_actions_0ewpun6.js")
R.m(985999)
module.exports=R.m(985999).exports
