var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/reputation/alerts/route.js")
R.c("server/chunks/[root-of-the-server]__0hgsy95._.js")
R.c("server/chunks/_0isv7-9._.js")
R.c("server/chunks/[root-of-the-server]__0j2~4y-._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_next-internal_server_app_api_reputation_alerts_route_actions_0o.6nte.js")
R.m(206121)
module.exports=R.m(206121).exports
