var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/signals/route.js")
R.c("server/chunks/[root-of-the-server]__0vruly9._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/[root-of-the-server]__05smt~n._.js")
R.c("server/chunks/node_modules_0.81f0j._.js")
R.c("server/chunks/_0k0ysmc._.js")
R.c("server/chunks/_03ejtys._.js")
R.c("server/chunks/_0.k7p5x._.js")
R.c("server/chunks/_next-internal_server_app_api_signals_route_actions_0hrech6.js")
R.m(18672)
module.exports=R.m(18672).exports
